name: Say Hello

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: false
        default: "stranger"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, ${{ github.event.inputs.name }}!"
