name: Start Game

on:
  workflow_dispatch:
    inputs:
      players:
        description: "Comma-separated list of player names (e.g. Jay,Paul)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  start:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies (if needed)
        run: pip install -r ../requirements.txt || true

      - name: Start game
        run: |
          mkdir -p games
          python start_game.py "${{ github.event.inputs.players }}"

      - name: Commit game file to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull
          git add games/
          git commit -m "🎮 Start game with players: ${{ github.event.inputs.players }}" || echo "Nothing to commit"
          git push
